language: csharp
dist: bionic
mono: none
services:
  - docker
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
before_script:
  - chmod -R a+x scripts
script:
  - "./scripts/travis-build.sh"
before_deploy:
    - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: bash ./scripts/travis-deploy.sh
  on:
    tags: true
    branch: master
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+(\\.[0-9])?$"
notifications:
  email:
    on_success: never
    on_failure: always
